.github/workflows/assign-random-reviewers.yml
PR 생성자를 Asignee로 추가하는 로직 코드를 작성
- close #9
=> 🔧 Chore:#9 github Action 설정파일 수정

eslint.config.js, package-lock.json, package.json, prettier.config.mjs, src/controllers/auth.controller.ts, src/types/common.types.ts, tsconfig.json
=> 컨트롤러의 request body의 형식을 설정

.github/workflows/assign-random-reviewers.yml
=> 깃헙 액션 설정 파일 수정

.gitignore
=> .gitignore에 ec2 관련 민감정보 추가

src/configs/aws.config.ts, src/configs/common.config.ts, src/configs/postgres.config.ts
=> 환경변수 세팅 여부 검증

.github/workflows/slack-alarm-webhook.yml
=> 🔧 Chore: 액션 조건 변경

.github/workflows/assign-random-reviewers.yml, .github/workflows/deploy.yml, .github/workflows/slack-alarm-webhook.yml, src/configs/common.config.ts
- close #61
배포 서버 환경변수 및 배포 코드 수정
=> 배포 서버 환경변수 및 배포 코드 수정

.github/workflows/slack-alarm-webhook.yml
=> 깃헙 액션 긴급 수정

src/controllers/work.controller.ts, src/middlewares/jwtValidation.ts, src/types/recipe.types.ts
서버 배포 테스트를 위해 에러가 나는 부분을 주석처리했습니다.
- close #이슈번호
=> 🐛 Fix: 에러 코드 주석처리

prisma/migrations/20241119120318_/migration.sql, prisma/schema.prisma, src/types/user.types.ts
=> 🐛 Fix: refresh token default

.github/workflows/deploy.yml
=> Dev to Main

.github/workflows/assign-issue-creater.yml
=> 이슈 생성자를 asignee로 자동 설정하게 세팅

src/controllers/challenge.controller.ts, src/middlewares/validateChallenge.ts, src/repositories/challenge.repository.ts, src/routes/challenge.route.ts, src/services/challenge.service.ts, src/types/challenge.types.ts, src/utils/struct.ts
- close #84
- 챌린지 수정(Patch) 기능 추가
=> 챌린지 수정(Patch) 기능 추가

.github/workflows/slack-alarm-webhook.yml, src/app.ts, src/utils/S3/generate-presigned-download-url.ts, src/utils/constants/messages.ts
- close #107
s3로부터 다운로드 받는 URL 생성
app.ts의 '/s3-download'로 접근하면 GoogleBtn.png의 서명 주소가 생성될 것.
=> s3로부터 다운로드 받는 URL 생성

src/app.ts, src/utils/S3/generate-presigned-upload-url.ts, src/utils/constants/messages.ts
- close #109
S3 presigned Upload Url 생성
=> S3에 업로드하는 url 발급

src/repositories/feedback.repository.ts
- close #115
피드백에 소유자 이름 추가해서 보냄
=> 피드백에 소유자 이름 추가

src/controllers/challenge.controller.ts, src/interfaces/repositories/challenge.repository.interface.ts, src/interfaces/services/challenge.service.interface.ts, src/repositories/challenge.repository.ts, src/routes/challenge.route.ts, src/services/challenge.service.ts
- close #112
챌린지 반려사유 조회 api 생성
=> 챌린지 반려사유 조회 api 생성

src/controllers/recipe.controller.ts, src/repositories/recipe.repository.ts, src/types/recipe.types.ts
=> 레시피에 키워드 쿼리 추가

.github/workflows/deploy.yml, src/middlewares/token.verifier.ts
=> 배포 도중 긴급 수정

src/controllers/recipe.controller.ts, src/types/recipe.types.ts
- close #147
레시피 목록 호출 시 쿼리 변경
=> 레시피 호출 필터 변경

src/services/auth.service.ts, src/utils/constants/messages.ts
=> 유저 가입 시도시 중복 메시지

src/repositories/work.repository.ts, src/types/recipe.types.ts
=> 🐛 Fix: 레시피 dto 문제 해결

src/controllers/challenge.controller.ts, src/services/challenge.service.ts, src/utils/constants/messages.ts, src/utils/validateUpdateStatus.ts
- close #153 
챌린지 API: 에러 메시지 및 상태 코드 추가
=> 챌린지 API: 에러 메시지 및 상태 코드 추가

package-lock.json, package.json, src/app.ts, src/utils/jobs/challengeJob.ts, src/utils/jobs/index.ts
- close #156
deadline기준으로 ongoing 상태의 챌린지를 finished로 자동 변경 스케줄링
=> deadline기준으로 ongoing 상태의 챌린지를 finished로 자동 변경 스케줄링

src/middlewares/token.verifier.ts, src/utils/struct.ts
- close #171
invalid token시 서버 죽는거 해결
feedback superstruct 오류 해결
=> 에러 핸들러 재조정 및 superstruct 수정

prisma/migrations/20241128003701_add_like_recipe/migration.sql, prisma/migrations/20241128004310_like_default_0/migration.sql, prisma/schema.prisma, src/controllers/recipe.controller.ts, src/interfaces/repositories/recipe.repository.interface.ts, src/interfaces/services/recipe.service.interface.ts, src/repositories/recipe.repository.ts, src/routes/recipe.route.ts, src/services/recipe.service.ts
=> 레시피 좋아요 구현

prisma/mock/recipeMock.ts, src/services/recipe.service.ts
=> 레시피 이미지 관련 처리

src/services/challenge.service.ts
- close #187 
이달의 챌린지 이미지 반환 s3key -> downloadUrl
=> 이달의 챌린지 이미지 반환 s3key -> downloadUrl

src/services/work.service.ts
프론트의 요청으로 3 관리자의 작업물 삭제 권한 추가
- close #203 
프론트의 요청으로 관리자의 작업물 삭제 권한 추가
=> ✨ Feat #203 관리자의 작업물 삭제 권한 추가

src/repositories/recipe.repository.ts
=> 레시피 조회시 좋아요 유저 출력

src/controllers/challenge.controller.ts, src/interfaces/repositories/challenge.repository.interface.ts, src/repositories/challenge.repository.ts, src/routes/challenge.route.ts, src/services/challenge.service.ts, src/types/challenge.types.ts
=> 이전/다음 챌린지 조회

src/repositories/challenge.repository.ts
- close #-
다음/이전 챌린지 조회시 리퀘스트 유저 정보 포함
=> 리퀘스트 유저 정보 포함

src/repositories/challenge.repository.ts
=> ✨ Feat: 참여자 정보 포함

src/controllers/challenge.controller.ts
=> 미디어 타입 쿼리 추가 및 필터 수정

prisma/mock/challengeMock.ts, prisma/seed.ts
- close #226
work 시딩시 참여자 연결 문제 해결
=> work 시딩시 참여자 연결 문제 해결

package-lock.json, package.json, src/configs/auth.config.ts, src/utils/nodemailer/transport-option.ts, src/utils/nodemailer/transporter.ts
=> 노드메일러 기본 세팅

src/app.ts, src/interfaces/services/work.service.interface.ts, src/repositories/work.repository.ts, src/services/work.service.ts, src/types/work.types.ts, src/utils/changeTypeWork.ts
=> ♻️ Refactor: 작업물 생성 형식 챌린지와 통일

prisma/seed.ts
=> ⏪️ Revert: 챌린지 시드 롤백

src/controllers/auth.controller.ts
=> 🐛 Fix: 리프레시 토큰을 쿠키로

package-lock.json, src/containers/feedback.container.ts, src/controllers/challenge.controller.ts, src/controllers/feedback.controller.ts, src/controllers/recipe.controller.ts, src/controllers/user.controller.ts, src/controllers/work.controller.ts, src/interfaces/repositories/feedback.repository.interface.ts, src/repositories/feedback.repository.ts, src/services/feedback.service.ts, src/services/work.service.ts, src/utils/constants/messages.ts
- close #238
목록 조회시 상위 리소스가 존재하는지 여부 체크
=> 목록 조회시 상위 리소스 확인

src/controllers/auth.controller.ts
=> ⏪️ Revert:#249 리프레시 토큰을 다시 응답 바디로

src/controllers/auth.controller.ts, src/middlewares/token.verifier.ts, src/services/auth.service.ts
- close #252
리프레시할 때 리프레시 토큰을 쿠키 대신 바디에서 받도록.
-> 리프레시 방식 자체 변경
=> 🐛 Fix: refreshToken to body

src/app.ts, src/containers/challenge.container.ts, src/containers/notification.container.ts, src/repositories/challenge.repository.ts, src/repositories/notification.repository.ts, src/services/challenge.service.ts, src/services/notification.service.ts, src/types/challenge.types.ts, src/utils/jobs/challengeJob.ts, src/utils/socket/finishedNotification.ts, src/utils/socket/index.ts, src/utils/socket/socket.utils.ts
- close #236
finished 알림 리팩토링
너무 힘들어용 ㅠ
그만하고 싶엉 ㅠ
=> finished 알림 리팩토링

src/containers/verify.container.ts
=> 🐛 Fix: 핫픽스 241204

docker/.dockerignore, docker/Dockerfile, docker/db.docker-compose.yaml, docker/docker-compose.yaml, src/containers/verify.container.ts
도커파일 및 컴포즈 파일 작성
- close #247 
도커파일 및 컴포즈 파일 작성
dev pull 해도 오류가 고쳐지지 않아  verify 컨테이너 수정했습니다
=> ✨ Feat #247 도커파일 작성

src/app.ts
- close #260
socket 서버 cors 추가
- 서버 배포 다시 해주시면 감사하겠습니다! ㅠㅠ
=> 🐛 Fix: socket 서버 cors 추가

src/app.ts, src/services/feedback.service.ts
- close #262
내 작업물에 피드백 달리면 알림 설정
=> 내 작업물에 피드백 달리면 알림 설정

src/interfaces/repositories/notification.repository.interface.ts, src/repositories/notification.repository.ts, src/services/notification.service.ts, src/utils/jobs/challengeJob.ts
- close #264
notification get 수정
=> ✨ Feat: get notification 정렬 추가

src/controllers/notification.controller.ts, src/repositories/notification.repository.ts, src/routes/notification.route.ts, src/services/notification.service.ts, src/types/notification.types.ts, src/utils/struct.ts
- close #266
notification isRead update api 생성
=> ✨ Feat: notification isRead update api 생성

prisma/migrations/20241205083218_add_notification_work_id_field/migration.sql, prisma/schema.prisma, src/containers/feedback.container.ts, src/repositories/notification.repository.ts, src/services/feedback.service.ts, src/services/notification.service.ts, src/utils/jobs/challengeJob.ts
- close #268
feedback 실시간 알림시 challengeId도 넘겨주기
스키마 수정해서 마이그레이션 한번씩 해주세요!
=> feedback 실시간 알림시 challengeId도 넘겨주기

docker/docker-compose.app1.yaml, docker/docker-compose.app2.yaml, docker/docker-compose.nginx.yaml, docker/nginx.conf
- close #269 
ec2 instance 안에서 nginx를 이용해 로드밸런싱을 컨테이너 형태의 컴포즈로 구현
=> ✨ Feat #269 Docker Compose를 이용한 다중 컨테이너 환경에서 Nginx 로드밸런싱 구성

src/utils/jobs/challengeJob.ts
=> 🐛 Fix: cron 시간 변경

src/services/work.service.ts, src/types/work.types.ts, src/utils/changeTypeWork.ts
- close #274 
리스폰스에서 imageUrl 제외
=> ♻️ 리스폰스 수정,생성과 수정 시  imageUrl 제거

src/app.ts
- close #268
credentials: true
=> credentials: true

src/services/feedback.service.ts
- close #268
- 
feedback 소켓 대상 변경
=> feedback 소켓 대상 변경 

docker/nginx.conf
=> 🐛 Fix #280 nginx에서 웹소켓통신 처리

README.md
- close #282
📝 Docs: 김민선 경로 수정
=> 📝 Docs: 김민선 경로 수정

prisma/mock/challengeMock.ts, src/repositories/challenge.repository.ts, src/services/challenge.service.ts
=> Fix: 다음 챌린지 조회

src/repositories/challenge.repository.ts
=> Fix: 관리자 이달의 챌린지 문제

src/utils/nodemailer/verification-message.ts
=> Fix: verify link

prisma/schema.prisma, src/controllers/auth.controller.ts
=> Fix: 스키마 롤백된거 다시 추가

src/utils/nodemailer/verification-message.ts
=> Fix: local to ec2

README.md
- close #282
Docs: 프론트 사이트 재배포 주소 변경
=> 📝 Docs: 프론트 사이트 재배포 주소 변경

README.md
- close #282
Docs: 기술 스택 변경 추가
=> 📝 Docs: 기술 스택 변경 추가

README.md
- close #302
📝 Docs: 기술 스택 업데이트
=> 📝 Docs: 기술 스택 업데이트

src/app.ts
- close #302
Refactor: cors 경로 재설정
=> ♻️ Refactor: cors 경로 재설정

src/app.ts, src/configs/common.config.ts
=> ♻️ Refactor: cors 경로 refactor
